# coding=utf-8
# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    'src/python/pants.standalone.native/config',
    'src/python/pants.standalone.native/subsystems',
    'src/python/pants.standalone.native/subsystems/binaries',
    'src/python/pants.standalone.native/targets',
    'src/python/pants.standalone.native/tasks',
    'src/python/pants/build_graph',
    'src/python/pants/goal:task_registrar',
  ],
)
