# Conditions are documented here: https://docs.travis-ci.com/user/conditions-v1
conditions: v1

env:
  global:
    - PANTS_CONFIG_FILES="${TRAVIS_BUILD_DIR}/pants.travis-ci.ini"
    - PYTEST_PASSTHRU_ARGS="-v --duration=3"

before_cache:
  # Ensure permissions to do the below removals, which happen with or without caching enabled.
  - sudo chown -R travis:travis "${HOME}" "${TRAVIS_BUILD_DIR}"
  # Kill all python bytecode in our cached venvs.  Some files appear to
  # get bytecode compiled in non-yet-understood circumstances leading to
  # a full cache re-pack due to new bytecode files.
  - find build-support -name "*.py[co]" -delete
  # The `ivydata-*.properties` & root level `*.{properties,xml}` files'
  # effect on resolution time is in the noise, but they are
  # re-timestamped in internal comments and fields on each run and this
  # leads to travis-ci cache thrash.  Kill these files before the cache
  # check to avoid un-needed cache re-packing and re-upload (a ~100s
  # operation).
  - find ${HOME}/.ivy2/pants -type f -name "ivydata-*.properties" -delete
  - rm -f ${HOME}/.ivy2/pants/*.{css,properties,xml,xsl}
  # We have several tests that do local file:// url resolves for
  # com.example artifacts, these disrupt the cache but are fast since
  # they're resolved from local files when omitted from the cache.
  - rm -rf ${HOME}/.ivy2/pants/com.example
  # The stats cache contains timestamped reports unused by CI but that
  # thrash the cache.  Skip caching these.
  - rm -rf ${HOME}/.cache/pants/stats
  # While the bin directory and rust toolchains are relatively large, they're also very quick to
  # restore/install: prune them to keep the total cache size down.
  #   see https://docs.travis-ci.com/user/caching/#Things-not-to-cache
  # NB: We do _not_ prune the cargo cache, since that holds compiled tools and outputs, and
  # individually resolved artifacts.
  - rm -rf ${HOME}/.cache/pants/bin
  - rm -rf ${HOME}/.cache/pants/rust/rustup
  - rm -rf ${HOME}/.cache/pants/lmdb_store
  # Render a summary of what is left in the home directory, to assist with further pruning of
  # the cache.
  - du -d2 ${HOME} | sort -r -n

cache:
  directories:
    - ${HOME}/.cache/pants
    - ${HOME}/.ivy2/pants
    # TODO(John Sirois): Update this to ~/.npm/pants when pants starts
    # using its own isolated cache:
    #   https://github.com/pantsbuild/pants/issues/2485
    - ${HOME}/.npm
    - build-support/isort.venv
    - build-support/pants_dev_deps.venv

# Stages are documented here: https://docs.travis-ci.com/user/build-stages
stages:
  - Test Pants
  - name: Deploy Pants Pex
    if: tag IS present AND tag =~ ^release_.*$

# NB: There is much repetition in include elements, but there is no known current way to factor
# this duplication up.
matrix:
  include:
    - os: osx
      # Fuse actually works on this image. It hangs on many others.
      osx_image: xcode8.3
      stage: Test Pants
      language: generic
      env:
        - SHARD="Rust + Platform-specific Tests OSX"
        # Specifically avoid the OSX provided 2.7.10 under xcode8.3 since it returns a platform
        # of `macosx-*-intel` where the `intel` suffix is bogus but pex has not yet been taught to
        # deal with this. Can be removed when this issue is resolved:
        # https://github.com/pantsbuild/pex/issues/523
        - PANTS_PYTHON_SETUP_INTERPRETER_CONSTRAINTS="['CPython>2.7.10,<3']"
      before_install:
        - brew tap caskroom/cask && brew update && brew cask install osxfuse
      before_script:
        - ulimit -c unlimited
        - ulimit -n 8192
      script:
        - ./pants test tests/python/pants_test/backend/python/tasks:python_native_code_testing -- -vsktest_invalidation
