python_library(
  dependencies=[
    'src/python/pants/backend/native',
    'src/python/pants/binaries:host_installed_tool',
    # 'src/python/pants/util:contextutil',
    # 'src/python/pants/util:memo',
  ],
)
