# coding=utf-8
# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  dependencies=[
    'src/python/pants/backend/native/subsystems',
    'src/python/pants/backend/native/rules',
    'src/python/pants/engine:fs',
    'src/python/pants/engine:rules',
    'src/python/pants/util:contextutil',
    'src/python/pants/util:process_handler',
    'tests/python/pants_test:base_test',
    'tests/python/pants_test/engine:scheduler_test_base',
    'tests/python/pants_test/subsystem:subsystem_utils',
  ],
)
