# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

ctypes_compatible_cpp_library(
  name='cpp-test-main',
  ctypes_native_library=native_artifact(exe_name='cpp-test-main'),
)
