# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


python_dist(
  sources=['pants_setup.py', 'hello.c'],
  setup_py_alternate_filename='pants_setup.py',
)
